var test = require('node:test');
var assert = require('node:assert/strict');
var http = require('http');
var fs = require('fs');
var path = require('path');

var publicRoot = path.resolve(__dirname, '../lib/public');
var markedFile = path.resolve(__dirname, '../node_modules/marked/marked.min.js');

function playwrightOrNull() { try { return require('playwright'); } catch (error) { return null; } }

function pageHtml() {
  return '<!doctype html><html><body><div id="session-actions"></div><div id="main-panels"><main id="chat">Chat remains</main></div>' +
    '<script src="/marked.js"></script><script>window.DOMPurify={sanitize:function(value){return value;}};window.mermaid={initialize:function(){},render:function(){return Promise.resolve({svg:""});}};window.hljs={highlightElement:function(){}};window.lucide={createIcons:function(){}};</script>' +
    '<script type="module">import {createStore,store} from "/modules/store.js";import {setWs} from "/modules/ws-ref.js";import {initMateKnowledgeWorkbench,openKnowledgeWorkbench,handleKnowledgeWorkbenchMessage} from "/modules/mate-knowledge-workbench.js";' +
    'createStore({currentSlug:"mate-fixture",projectsHubList:[{slug:"mate-fixture",isMate:true}],cachedMatesList:[],mateKnowledgeWorkspaces:{},rightWorkbenchRevision:0});window.sent=[];window.setKnowledgeWs=setWs;setWs({readyState:1,send:function(raw){window.sent.push(JSON.parse(raw));}});window.knowledge={store:store,handle:handleKnowledgeWorkbenchMessage};initMateKnowledgeWorkbench();openKnowledgeWorkbench();window.ready=true;</script></body></html>';
}

function serve(t) {
  var server = http.createServer(function (request, response) {
    var url = new URL(request.url, 'http://localhost');
    if (url.pathname === '/') { response.setHeader('Content-Type', 'text/html'); response.end(pageHtml()); return; }
    if (url.pathname === '/marked.js') { response.setHeader('Content-Type', 'text/javascript'); fs.createReadStream(markedFile).pipe(response); return; }
    var file = path.resolve(publicRoot, '.' + url.pathname);
    if (!file.startsWith(publicRoot + path.sep)) { response.writeHead(403); response.end(); return; }
    fs.readFile(file, function (error, data) { if (error) { response.writeHead(404); response.end(); return; } response.setHeader('Content-Type', file.endsWith('.css') ? 'text/css' : 'text/javascript'); response.end(data); });
  });
  t.after(function () { server.close(); });
  return new Promise(function (resolve) { server.listen(0, '127.0.0.1', function () { resolve(server); }); });
}

async function lastSent(page, type) {
  await page.waitForFunction(function (wanted) { return window.sent.some(function (item) { return item.type === wanted; }); }, type);
  return page.evaluate(function (wanted) { var matches = window.sent.filter(function (item) { return item.type === wanted; }); return matches[matches.length - 1]; }, type);
}

async function reply(page, message) {
  await page.evaluate(function (value) { window.knowledge.handle(value); }, message);
}

async function restoreDeleted(page, id, name, version) {
  await page.locator('[data-deleted-history="' + id + '"]').click(); var history = await lastSent(page, 'knowledge_history');
  assert.equal(history.documentId, id); await reply(page, { type: 'knowledge_history', requestId: history.requestId, versions: [{ version: version }] });
  await page.locator('[data-history-preview="' + version + '"]').click(); var read = await lastSent(page, 'knowledge_history_read');
  assert.equal(read.documentId, id); await reply(page, { type: 'knowledge_history_version', requestId: read.requestId, version: version, content: '# Historical ' + name });
  assert.equal(await page.locator('[data-history-restore]').count(), 0); await page.locator('[data-history-review]').click();
  assert.equal(await page.locator('.knowledge-editor-host').count(), 0); await page.locator('[data-history-restore]').click(); var restore = await lastSent(page, 'knowledge_restore');
  assert.deepEqual({ id: restore.documentId, name: restore.name, revision: restore.expectedRevision }, { id: id, name: name, revision: null });
  await reply(page, { type: 'knowledge_restored', requestId: restore.requestId, id: id, name: name, revision: 'restored-' + id }); var current = await lastSent(page, 'knowledge_read');
  assert.equal(current.documentId, id); await reply(page, { type: 'knowledge_content', requestId: current.requestId, id: id, name: name, revision: 'restored-' + id, writable: true, content: '# Restored ' + name, outgoing: [], backlinks: [] });
  await page.getByText('Restored ' + name, { exact: true }).waitFor(); assert.equal(await page.locator('[data-deleted-history="' + id + '"]').count(), 0);
}

test('production Knowledge controller owns delayed history, preview links, deleted restore, and search pages', { timeout: 120000 }, async function (t) {
  var playwright = playwrightOrNull(); if (!playwright) { t.skip('playwright is not installed'); return; }
  var browser; try { browser = await playwright.chromium.launch(); } catch (error) { t.skip('Chromium is not available: ' + error.message); return; }
  t.after(function () { return browser.close(); }); var server = await serve(t); var page = await browser.newPage({ viewport: { width: 1280, height: 800 } });
  await page.goto('http://127.0.0.1:' + server.address().port); await page.waitForFunction(function () { return window.ready; });
  var list = await lastSent(page, 'knowledge_list'); var files = [{ id: 'a', name: 'A.md', revision: 'rev-a' }, { id: 'b', name: 'B.md', revision: 'rev-b' }, { id: 'doc', name: 'Doc.md', revision: 'rev-doc' }];
  await reply(page, { type: 'knowledge_list', requestId: list.requestId, files: files, drafts: [] });
  await page.getByRole('button', { name: 'A', exact: true }).click(); var readA = await lastSent(page, 'knowledge_read');
  await reply(page, { type: 'knowledge_content', requestId: readA.requestId, id: 'a', name: 'A.md', revision: 'rev-a', writable: true,
    content: '<https://example.com>\n\n<a href="Doc.md">Raw</a>\n\n[Doc](Doc.md)\n\n[[javascript:alert(1)]]\n\n\\[[escaped]]\n\n`[[code]]`',
    outgoing: [{ kind: 'markdown', target: 'Doc.md', label: 'Doc', documentKey: 'local:doc' }, { kind: 'wiki', target: 'javascript:alert(1)', label: 'unsafe', raw: '[[javascript:alert(1)]]', external: true }], backlinks: [] });
  assert.equal(await page.locator('.knowledge-preview a[href^="https://example.com"]').count(), 1);
  assert.equal(await page.locator('.knowledge-preview [data-open-document="local:doc"]').count(), 1);
  assert.equal(await page.locator('.knowledge-preview a[href="Doc.md"][data-open-document]').count(), 0);
  assert.equal(await page.locator('.knowledge-preview a[href^="javascript:"]').count(), 0);

  await page.locator('[data-history-load]').click(); var delayedA = await lastSent(page, 'knowledge_history');
  await page.getByRole('button', { name: 'B', exact: true }).click(); var readB = await lastSent(page, 'knowledge_read');
  await reply(page, { type: 'knowledge_content', requestId: readB.requestId, id: 'b', name: 'B.md', revision: 'rev-b', writable: true, content: '# B current', outgoing: [], backlinks: [] });
  await reply(page, { type: 'knowledge_history', requestId: delayedA.requestId, versions: [{ version: '1000-a' }] });
  assert.match(await page.locator('[role="tab"][aria-selected="true"]').innerText(), /B/); await page.locator('[data-history-preview="1000-a"]').click(); var versionA = await lastSent(page, 'knowledge_history_read');
  assert.equal(versionA.documentId, 'a'); await reply(page, { type: 'knowledge_history_version', requestId: versionA.requestId, version: '1000-a', content: '# A historical' });
  assert.match(await page.locator('.knowledge-document-toolbar').innerText(), /A\.md/); assert.equal(await page.locator('[data-history-restore]').count(), 0);
  await page.locator('[data-history-review]').click(); assert.equal(await page.locator('.knowledge-editor-host').count(), 0); await page.locator('[data-history-restore]').click(); var restoreA = await lastSent(page, 'knowledge_restore');
  assert.deepEqual({ id: restoreA.documentId, name: restoreA.name, revision: restoreA.expectedRevision }, { id: 'a', name: 'A.md', revision: 'rev-a' });
  await reply(page, { type: 'knowledge_restored', requestId: restoreA.requestId, id: 'a', name: 'A.md', revision: 'rev-a2' }); var refreshedA = await lastSent(page, 'knowledge_read');
  await reply(page, { type: 'knowledge_content', requestId: refreshedA.requestId, id: 'a', name: 'A.md', revision: 'rev-a2', writable: true, content: '# A restored actual', outgoing: [], backlinks: [] });
  await page.getByText('A restored actual', { exact: true }).waitFor();

  await page.locator('[data-knowledge-deleted]').click(); var deletedList = await lastSent(page, 'knowledge_deleted_list');
  await reply(page, { type: 'knowledge_deleted_list', requestId: deletedList.requestId, files: [{ id: 'gone-b', name: 'gone-b.md' }, { id: 'gone-empty', name: 'gone-empty.md' }] });
  await page.getByRole('button', { name: 'B', exact: true }).click(); await restoreDeleted(page, 'gone-b', 'gone-b.md', '2000-b');
  var closeButtons = page.locator('[data-close-tab]'); while (await closeButtons.count()) await closeButtons.first().click();
  await restoreDeleted(page, 'gone-empty', 'gone-empty.md', '3000-empty');

  var search = page.getByRole('searchbox'); await search.fill('result'); await page.waitForTimeout(220); var searchOne = await lastSent(page, 'knowledge_search'); assert.equal(searchOne.offset, 0); assert.equal(searchOne.limit, 50);
  var pageOne = []; for (var i = 1; i <= 50; i++) pageOne.push({ id: 'r' + i, name: 'result-' + i + '.md' });
  await reply(page, { type: 'knowledge_search_results', requestId: searchOne.requestId, files: pageOne, total: 51, complete: true }); await page.locator('[data-search-more]').click(); var searchTwo = await lastSent(page, 'knowledge_search'); assert.equal(searchTwo.offset, 50);
  await reply(page, { type: 'knowledge_search_results', requestId: searchTwo.requestId, files: [{ id: 'r51', name: 'result-51.md' }], total: 51, complete: true }); assert.equal(await page.getByRole('button', { name: 'result-51', exact: true }).count(), 1);

  await search.fill(''); await page.getByRole('button', { name: 'A', exact: true }).click(); await page.locator('[data-document-action="edit"]').click(); await page.locator('.knowledge-editor-fallback').fill('[Other](Other.md)');
  assert.equal(await page.locator('.knowledge-live-preview [data-open-document]').count(), 0);
});

test('production Knowledge controller keeps database tables read only, edits fullscreen, and owns delayed replies', { timeout: 120000 }, async function (t) {
  var playwright = playwrightOrNull(); if (!playwright) { t.skip('playwright is not installed'); return; }
  var browser; try { browser = await playwright.chromium.launch(); } catch (error) { t.skip('Chromium is not available: ' + error.message); return; }
  t.after(function () { return browser.close(); }); var server = await serve(t); var page = await browser.newPage({ viewport: { width: 1280, height: 800 } });
  await page.goto('http://127.0.0.1:' + server.address().port); await page.waitForFunction(function () { return window.ready; });
  var list = await lastSent(page, 'knowledge_list'); var database = { id: 'db_12345678', itemType: 'db', name: 'Cases', revision: 3, writable: true, recordCount: 1,
    schema: [{ id: 'fld_title001', name: 'Name" autofocus onfocus="window.pwn=1', type: 'title', required: true, archived: false }, { id: 'fld_number01', name: 'Score', type: 'number', required: false, archived: false }],
    views: [{ id: 'view_table01', name: 'Table', type: 'table', columns: ['fld_title001', 'fld_number01'], filters: [], sorts: [], archived: false }] };
  await reply(page, { type: 'knowledge_list', requestId: list.requestId, files: [{ id: 'doc', name: 'Doc.md', revision: 'r1', itemType: 'text' }, database], drafts: [] });
  await page.getByRole('button', { name: 'Cases', exact: true }).click(); var read = await lastSent(page, 'knowledge_db_read'); assert.equal(read.databaseId, database.id);
  await page.getByRole('button', { name: 'Doc', exact: true }).click(); var docRead = await lastSent(page, 'knowledge_read');
  await reply(page, { type: 'knowledge_db_content', requestId: read.requestId, database: database }); var query = await lastSent(page, 'knowledge_db_query'); assert.equal(query.viewId, 'view_table01');
  await reply(page, { type: 'knowledge_db_query_results', requestId: query.requestId, databaseId: database.id, databaseRevision: 3, records: [{ id: 'rec_12345678', revision: 1, values: { fld_title001: 'Alpha" onclick="window.pwn=2', fld_number01: 7 }, updatedAt: 1 }, { id: 'rec_87654321', revision: 1, values: { fld_title001: 'Beta', fld_number01: 2 }, updatedAt: 1 }], totals: { count: 2, sums: { fld_number01: 9 } }, nextCursor: null });
  await reply(page, { type: 'knowledge_content', requestId: docRead.requestId, id: 'doc', name: 'Doc.md', revision: 'r1', writable: true, content: '# Document stays selected', outgoing: [], backlinks: [] });
  assert.match(await page.locator('[role="tab"][aria-selected="true"]').innerText(), /Doc/);
  await page.getByRole('button', { name: 'Cases', exact: true }).click();
  assert.equal(await page.locator('.knowledge-db-table input').count(), 0); assert.equal(await page.locator('#mate-knowledge-workbench').getAttribute('class'), ''); assert.equal(await page.locator('[onfocus], [onclick]').count(), 0); assert.equal(await page.evaluate(function () { return window.pwn; }), undefined);
  await page.locator('[data-db-record="rec_12345678"]').click(); var delayedAlpha = await lastSent(page, 'knowledge_db_record_read'); await reply(page, { type: 'knowledge_db_record_content', requestId: delayedAlpha.requestId, database: database, record: { id: 'rec_12345678', revision: 1, values: { fld_title001: 'Alpha', fld_number01: 7 }, updatedAt: 1 }, title: 'Alpha', history: [] }); await page.locator('[data-db-record-back]').click(); await page.evaluate(function () { window.sent = window.sent.filter(function (item) { return item.type !== 'knowledge_db_record_read'; }); }); await page.locator('[data-db-record="rec_87654321"]').click(); var delayedBeta = await lastSent(page, 'knowledge_db_record_read'); await reply(page, { type: 'knowledge_db_record_content', requestId: delayedAlpha.requestId, database: database, record: { id: 'rec_12345678', revision: 1, values: { fld_title001: 'Alpha', fld_number01: 7 }, updatedAt: 1 }, title: 'Alpha', history: [] }); assert.equal(await page.getByRole('heading', { name: 'Alpha' }).count(), 0); await reply(page, { type: 'knowledge_db_record_content', requestId: delayedBeta.requestId, database: database, record: { id: 'rec_87654321', revision: 1, values: { fld_title001: 'Beta', fld_number01: 2 }, updatedAt: 1 }, title: 'Beta', history: [] }); assert.equal(await page.getByRole('heading', { name: 'Beta' }).count(), 1); await page.locator('[data-db-record-back]').click(); await page.evaluate(function () { window.sent = window.sent.filter(function (item) { return item.type !== 'knowledge_db_record_read'; }); });
  await page.locator('[data-db-record="rec_12345678"]').click(); var recordRead = await lastSent(page, 'knowledge_db_record_read'); await reply(page, { type: 'knowledge_db_record_content', requestId: recordRead.requestId, database: database, record: { id: 'rec_12345678', revision: 1, values: { fld_title001: 'Alpha', fld_number01: 7 }, updatedAt: 1 }, title: 'Alpha', history: [] });
  assert.equal(await page.getByRole('heading', { name: 'Alpha' }).count(), 1); await page.locator('[data-db-edit-record]').click(); assert.match(await page.locator('#mate-knowledge-workbench').getAttribute('class'), /panel-fullscreen/);
  var title = page.locator('[data-db-field="fld_title001"]'); await title.fill('First save'); await page.locator('[data-db-save-record]').click(); var saveOne = await lastSent(page, 'knowledge_db_record_update'); assert.equal(saveOne.values.fld_title001, 'First save');
  await title.fill('Typed while saving'); await reply(page, { type: 'knowledge_db_record_updated', requestId: saveOne.requestId, databaseRevision: 4, record: { id: 'rec_12345678', revision: 2, values: { fld_title001: 'First save', fld_number01: 7 }, updatedAt: 2 } });
  assert.match(await page.locator('#mate-knowledge-workbench').getAttribute('class'), /panel-fullscreen/); assert.equal(await page.locator('[data-db-field="fld_title001"]').inputValue(), 'Typed while saving');
  await page.locator('[data-db-save-record]').click(); var saveTwo = await lastSent(page, 'knowledge_db_record_update'); assert.equal(saveTwo.expectedRevision, 2); assert.equal(saveTwo.values.fld_title001, 'Typed while saving');
  await reply(page, { type: 'knowledge_db_record_updated', requestId: saveTwo.requestId, databaseRevision: 5, record: { id: 'rec_12345678', revision: 3, values: { fld_title001: 'Typed while saving', fld_number01: 7 }, updatedAt: 3 } }); assert.doesNotMatch(await page.locator('#mate-knowledge-workbench').getAttribute('class'), /panel-fullscreen/);
  assert.equal(await page.locator('[data-db-archive-record]').count(), 0, 'archive is not offered in the normal workbench'); await page.locator('[data-db-edit-record]').click();
  await page.locator('[data-db-archive-record]').click(); assert.equal(await page.locator('.knowledge-db-dialog').count(), 1); assert.equal(await page.locator('.knowledge-layout').evaluate(function (element) { return element.inert; }), true); await page.locator('[data-db-dialog-cancel]').click(); assert.equal(await page.locator('.knowledge-db-dialog').count(), 0); assert.equal(await page.locator('.knowledge-layout').evaluate(function (element) { return element.inert; }), false); await page.waitForFunction(function () { return document.activeElement && document.activeElement.hasAttribute('data-db-archive-record'); });
  await page.evaluate(function () { window.setKnowledgeWs({ readyState: 1, send: function (raw) { window.failedDatabasePayload = JSON.parse(raw); throw new Error('offline'); } }); }); await page.locator('[data-db-field="fld_title001"]').fill('Offline draft'); await page.locator('[data-db-save-record]').click(); await page.getByText('Reconnect to save this record.', { exact: true }).waitFor(); var failedOperation = await page.evaluate(function () { return window.failedDatabasePayload.operationId; }); await page.evaluate(function () { window.setKnowledgeWs({ readyState: 1, send: function (raw) { window.sent.push(JSON.parse(raw)); } }); }); await page.locator('[data-db-save-record]').click(); var retried = await lastSent(page, 'knowledge_db_record_update'); assert.equal(retried.operationId, failedOperation); assert.equal(retried.values.fld_title001, 'Offline draft');
  await page.locator('[data-knowledge-new]').click(); assert.equal(await page.getByRole('menuitem', { name: /New document/ }).count(), 1); assert.equal(await page.getByRole('menuitem', { name: /New database/ }).count(), 1);
});

test('production database drafts preserve complex views, stable options, and fullscreen mutation review', { timeout: 120000 }, async function (t) {
  var playwright = playwrightOrNull(); if (!playwright) { t.skip('playwright is not installed'); return; }
  var browser; try { browser = await playwright.chromium.launch(); } catch (error) { t.skip('Chromium is not available: ' + error.message); return; }
  t.after(function () { return browser.close(); }); var server = await serve(t); var page = await browser.newPage({ viewport: { width: 1280, height: 800 } });
  await page.goto('http://127.0.0.1:' + server.address().port); await page.waitForFunction(function () { return window.ready; }); var list = await lastSent(page, 'knowledge_list');
  var filters = [{ fieldId: 'fld_score001', op: 'gte', value: 2 }, { fieldId: 'fld_status01', op: 'eq', value: 'opt_open001' }]; var sorts = [{ fieldId: 'fld_score001', direction: 'desc' }, { fieldId: 'fld_title001', direction: 'asc' }];
  var database = { id: 'db_complex01', itemType: 'db', name: 'Complex', revision: 3, writable: true, recordCount: 0,
    schema: [{ id: 'fld_title001', name: 'Name', type: 'title', required: true, archived: false }, { id: 'fld_score001', name: 'Score', type: 'number', required: false, archived: false }, { id: 'fld_status01', name: 'Status', type: 'select', required: false, archived: false, options: [{ id: 'opt_open001', name: 'Open', archived: false }, { id: 'opt_closed01', name: 'Closed', archived: false }] }],
    views: [{ id: 'view_complex1', name: 'Complex view', type: 'table', columns: ['fld_title001', 'fld_score001', 'fld_status01'], filters: filters, sorts: sorts, archived: false }] };
  await reply(page, { type: 'knowledge_list', requestId: list.requestId, files: [{ id: 'doc', name: 'Doc.md', revision: 'r1', itemType: 'text' }, database], drafts: [] }); await page.getByRole('button', { name: 'Complex', exact: true }).click(); var read = await lastSent(page, 'knowledge_db_read'); await reply(page, { type: 'knowledge_db_content', requestId: read.requestId, database: database }); var query = await lastSent(page, 'knowledge_db_query'); await reply(page, { type: 'knowledge_db_query_results', requestId: query.requestId, databaseId: database.id, databaseRevision: 3, records: [], totals: { count: 0, sums: {} }, nextCursor: null });
  await page.locator('[data-db-edit-views]').click(); await page.locator('[data-view-name]').fill('Renamed without loss'); await page.locator('[data-view-column][value="fld_status01"]').uncheck(); await page.locator('[data-db-save-view]').click(); var savedView = await lastSent(page, 'knowledge_db_view_save'); assert.deepEqual(savedView.view.filters, filters); assert.deepEqual(savedView.view.sorts, sorts); assert.deepEqual(savedView.view.columns, ['fld_title001', 'fld_score001']);
  var renamedView = Object.assign({}, database.views[0], { name: savedView.view.name, columns: savedView.view.columns }); database = Object.assign({}, database, { revision: 4, views: [renamedView] }); await reply(page, { type: 'knowledge_db_view_saved', requestId: savedView.requestId, database: database });
  await page.locator('[data-db-edit-schema]').click(); assert.equal(await page.locator('[data-schema-options]').count(), 0); assert.equal(await page.locator('[data-schema-option-name]').count(), 2); await page.locator('[data-schema-option-name][data-option-id="opt_closed01"]').fill('Done'); await page.locator('[data-schema-option-archived][data-option-id="opt_open001"]').check(); await page.locator('[data-db-save-schema]').click(); var savedSchema = await lastSent(page, 'knowledge_db_schema_save'); var savedStatus = savedSchema.schema.filter(function (field) { return field.id === 'fld_status01'; })[0]; assert.deepEqual(savedStatus.options, [{ id: 'opt_open001', name: 'Open', archived: true }, { id: 'opt_closed01', name: 'Done', archived: false }]);
  await page.locator('[data-db-cancel-edit]').click(); await page.locator('[data-db-settings]').click(); await page.locator('[data-db-settings-name]').fill('Renamed complex'); await page.locator('[data-db-save-settings]').click(); var rename = await lastSent(page, 'knowledge_db_rename'); await page.getByRole('button', { name: 'Doc', exact: true }).click(); var renameDocRead = await lastSent(page, 'knowledge_read'); await reply(page, { type: 'knowledge_content', requestId: renameDocRead.requestId, id: 'doc', name: 'Doc.md', revision: 'r1', writable: true, content: '# Rename owner', outgoing: [], backlinks: [] }); await page.locator('[data-document-action="edit"]').click(); database = Object.assign({}, database, { name: 'Renamed complex', revision: 5 }); await reply(page, { type: 'knowledge_db_renamed', requestId: rename.requestId, database: database }); assert.match(await page.locator('[role="tab"][aria-selected="true"]').innerText(), /Doc/); assert.match(await page.locator('#mate-knowledge-workbench').getAttribute('class'), /panel-fullscreen/);
  await page.locator('[data-document-action="read"]').click(); await page.getByRole('button', { name: 'Renamed complex', exact: true }).click(); await page.locator('[data-db-settings]').click(); await page.locator('[data-db-archive-database]').click(); await page.locator('[data-db-dialog-confirm]').click(); var archive = await lastSent(page, 'knowledge_db_archive'); await page.getByRole('button', { name: 'Doc', exact: true }).click(); await page.locator('[data-document-action="edit"]').click(); await reply(page, { type: 'knowledge_db_archived', requestId: archive.requestId, database: Object.assign({}, database, { revision: 6, archivedAt: 10 }) }); assert.match(await page.locator('[role="tab"][aria-selected="true"]').innerText(), /Doc/); assert.match(await page.locator('#mate-knowledge-workbench').getAttribute('class'), /panel-fullscreen/);
  await page.locator('[data-document-action="read"]').click(); await page.locator('[data-knowledge-new]').click(); await page.getByRole('menuitem', { name: /New database/ }).click(); await page.locator('[data-db-new-name]').fill('Draft database'); await page.locator('[data-knowledge-full]').click(); assert.equal(await page.locator('[data-db-new-name]').count(), 0); assert.equal(await page.locator('[data-db-resume-create]').count(), 1);
  await page.locator('[data-knowledge-close]').click(); await page.locator('#knowledge-workbench-btn').click(); var reopenedList = await lastSent(page, 'knowledge_list'); await reply(page, { type: 'knowledge_list', requestId: reopenedList.requestId, files: [{ id: 'doc', name: 'Doc.md', revision: 'r1', itemType: 'text' }, database], drafts: [] }); assert.equal(await page.locator('[data-db-new-name]').count(), 0); assert.equal(await page.locator('[data-db-resume-create]').count(), 1); await page.locator('[data-db-resume-create]').click(); assert.equal(await page.locator('[data-db-new-name]').inputValue(), 'Draft database'); await page.locator('[data-db-create-submit]').click(); var create = await lastSent(page, 'knowledge_db_create');
  await page.getByRole('button', { name: 'Doc', exact: true }).click(); var docRead = await lastSent(page, 'knowledge_read'); await reply(page, { type: 'knowledge_content', requestId: docRead.requestId, id: 'doc', name: 'Doc.md', revision: 'r1', writable: true, content: '# Keep me', outgoing: [], backlinks: [] }); await page.locator('[data-document-action="edit"]').click(); var createdDatabase = { id: 'db_created01', itemType: 'db', name: 'Draft database', revision: 1, writable: true, recordCount: 0, schema: [{ id: 'fld_created1', name: 'Name', type: 'title', required: true, archived: false }], views: [{ id: 'view_created', name: 'Table', type: 'table', columns: ['fld_created1'], filters: [], sorts: [], archived: false }] }; await reply(page, { type: 'knowledge_db_created', requestId: create.requestId, database: createdDatabase }); assert.match(await page.locator('[role="tab"][aria-selected="true"]').innerText(), /Doc/); assert.match(await page.locator('#mate-knowledge-workbench').getAttribute('class'), /panel-fullscreen/);
  await page.locator('[data-document-action="read"]').click(); await page.locator('[data-knowledge-deleted]').click(); var deleted = await lastSent(page, 'knowledge_deleted_list'); await reply(page, { type: 'knowledge_deleted_list', requestId: deleted.requestId, files: [{ id: 'db_archived1', itemType: 'db', name: 'Archived database', revision: 7 }] }); await page.locator('[data-db-recover-database="db_archived1"]').click(); assert.match(await page.locator('#mate-knowledge-workbench').getAttribute('class'), /panel-fullscreen/); assert.equal(await page.locator('.knowledge-db-dialog').count(), 0); assert.equal(await page.locator('[data-db-confirm-recover-database]').count(), 1); await page.locator('[data-db-confirm-recover-database]').click(); var recover = await lastSent(page, 'knowledge_db_recover');
  await page.getByRole('button', { name: 'Doc', exact: true }).click(); await page.locator('[data-document-action="edit"]').click(); var recoveredDatabase = Object.assign({}, createdDatabase, { id: 'db_archived1', name: 'Archived database', revision: 8 }); await reply(page, { type: 'knowledge_db_recovered', requestId: recover.requestId, database: recoveredDatabase }); assert.match(await page.locator('[role="tab"][aria-selected="true"]').innerText(), /Doc/); assert.match(await page.locator('#mate-knowledge-workbench').getAttribute('class'), /panel-fullscreen/);
});

test('production record drafts bind their record and retry immutable save attempts', { timeout: 120000 }, async function (t) {
  var playwright = playwrightOrNull(); if (!playwright) { t.skip('playwright is not installed'); return; }
  var browser; try { browser = await playwright.chromium.launch(); } catch (error) { t.skip('Chromium is not available: ' + error.message); return; }
  t.after(function () { return browser.close(); }); var server = await serve(t); var page = await browser.newPage({ viewport: { width: 1280, height: 800 } }); await page.goto('http://127.0.0.1:' + server.address().port); await page.waitForFunction(function () { return window.ready; });
  var list = await lastSent(page, 'knowledge_list'); var database = { id: 'db_records01', itemType: 'db', name: 'Records', revision: 3, writable: true, recordCount: 2, schema: [{ id: 'fld_title001', name: 'Name', type: 'title', required: true, archived: false }], views: [{ id: 'view_records1', name: 'Table', type: 'table', columns: ['fld_title001'], filters: [], sorts: [], archived: false }] };
  var rows = [{ id: 'rec_alpha001', revision: 1, values: { fld_title001: 'Alpha' }, updatedAt: 1 }, { id: 'rec_beta0001', revision: 1, values: { fld_title001: 'Beta' }, updatedAt: 1 }]; await reply(page, { type: 'knowledge_list', requestId: list.requestId, files: [database], drafts: [] }); await page.getByRole('button', { name: 'Records', exact: true }).click(); var read = await lastSent(page, 'knowledge_db_read'); await reply(page, { type: 'knowledge_db_content', requestId: read.requestId, database: database }); var query = await lastSent(page, 'knowledge_db_query'); await reply(page, { type: 'knowledge_db_query_results', requestId: query.requestId, databaseId: database.id, databaseRevision: 3, records: rows, totals: { count: 2, sums: {} }, nextCursor: null });
  await page.locator('[data-db-record="rec_alpha001"]').click(); var alphaRead = await lastSent(page, 'knowledge_db_record_read'); await reply(page, { type: 'knowledge_db_record_content', requestId: alphaRead.requestId, database: database, record: rows[0], title: 'Alpha', history: [] }); await page.locator('[data-db-edit-record]').click(); await page.locator('[data-db-field="fld_title001"]').fill('Alpha draft');
  await page.evaluate(function () { var store = window.knowledge.store; var all = Object.assign({}, store.get('mateKnowledgeDatabaseWorkspaces')); var workspace = Object.assign({}, all['mate-fixture']); var databases = Object.assign({}, workspace.databases); databases.db_records01 = Object.assign({}, databases.db_records01, { selectedRecord: 'rec_beta0001' }); workspace.databases = databases; all['mate-fixture'] = workspace; store.set({ mateKnowledgeDatabaseWorkspaces: all }); }); await page.locator('[data-db-save-record]').click(); var boundSave = await lastSent(page, 'knowledge_db_record_update'); assert.equal(boundSave.recordId, 'rec_alpha001');
  await reply(page, { type: 'knowledge_error', requestId: boundSave.requestId, error: 'Retry this save.' }); await page.evaluate(function () { window.setKnowledgeWs({ readyState: 1, send: function (raw) { window.ambiguousRecordPayload = JSON.parse(raw); throw new Error('ambiguous'); } }); }); await page.locator('[data-db-field="fld_title001"]').fill('Immutable first'); await page.locator('[data-db-save-record]').click(); var firstAttempt = await page.evaluate(function () { return window.ambiguousRecordPayload; }); await page.locator('[data-db-field="fld_title001"]').fill('Changed after attempt'); await page.evaluate(function () { window.setKnowledgeWs({ readyState: 1, send: function (raw) { window.sent.push(JSON.parse(raw)); } }); }); await page.locator('[data-db-save-record]').click(); var retry = await lastSent(page, 'knowledge_db_record_update'); assert.equal(retry.operationId, firstAttempt.operationId); assert.deepEqual(retry.values, firstAttempt.values);
  await reply(page, { type: 'knowledge_error', requestId: retry.requestId, error: 'Stop editing Alpha.' }); await page.locator('[data-db-cancel-edit]').click(); await page.locator('[data-db-record="rec_beta0001"]').click(); var betaRead = await lastSent(page, 'knowledge_db_record_read'); await reply(page, { type: 'knowledge_db_record_content', requestId: betaRead.requestId, database: database, record: rows[1], title: 'Beta', history: [] }); await page.locator('[data-db-record-back]').click(); await page.locator('[data-db-add-record]').click(); var createdTitle = page.locator('[data-db-field="fld_title001"]'); await createdTitle.fill('Created first'); await page.locator('[data-db-save-record]').click(); var create = await lastSent(page, 'knowledge_db_record_create'); await createdTitle.fill('Created later'); await createdTitle.evaluate(function (input) { input.focus(); input.setSelectionRange(4, 4); });
  var createdRecord = { id: 'rec_created01', revision: 1, values: { fld_title001: 'Created first' }, updatedAt: 2 }; await reply(page, { type: 'knowledge_db_record_created', requestId: create.requestId, databaseRevision: 4, record: createdRecord }); assert.equal(await page.locator('[data-db-field="fld_title001"]').inputValue(), 'Created later'); assert.equal(await page.evaluate(function () { var input = document.activeElement; return input && input.dataset.dbField === 'fld_title001' ? input.selectionStart : -1; }), 4);
  await page.locator('[data-db-save-record]').click(); var updateCreated = await lastSent(page, 'knowledge_db_record_update'); assert.equal(updateCreated.recordId, 'rec_created01'); assert.equal(updateCreated.expectedRevision, 1); assert.equal(updateCreated.values.fld_title001, 'Created later'); assert.notEqual(updateCreated.operationId, create.operationId);
  var finalRecord = { id: 'rec_created01', revision: 2, values: { fld_title001: 'Created later' }, updatedAt: 3 }; await reply(page, { type: 'knowledge_db_record_updated', requestId: updateCreated.requestId, databaseRevision: 5, record: finalRecord }); var reloadQuery = await lastSent(page, 'knowledge_db_query'); await page.locator('[data-db-record-back]').click(); await reply(page, { type: 'knowledge_db_query_results', requestId: reloadQuery.requestId, databaseId: database.id, databaseRevision: 5, records: [finalRecord], totals: { count: 1, sums: {} }, nextCursor: null }); assert.equal(await page.locator('[data-db-record]').count(), 1); assert.match(await page.locator('[data-db-record]').innerText(), /Created later/);
});

test('successful pending retries correlate duplicate acknowledgements and preserve later drafts', { timeout: 120000 }, async function (t) {
  var playwright = playwrightOrNull(); if (!playwright) { t.skip('playwright is not installed'); return; }
  var browser; try { browser = await playwright.chromium.launch(); } catch (error) { t.skip('Chromium is not available: ' + error.message); return; }
  t.after(function () { return browser.close(); }); var server = await serve(t); var page = await browser.newPage({ viewport: { width: 1280, height: 800 } }); await page.goto('http://127.0.0.1:' + server.address().port); await page.waitForFunction(function () { return window.ready; });
  var list = await lastSent(page, 'knowledge_list'); var database = { id: 'db_pending01', itemType: 'db', name: 'Pending', revision: 3, writable: true, recordCount: 1, schema: [{ id: 'fld_title001', name: 'Name', type: 'title', required: true, archived: false }], views: [{ id: 'view_pending1', name: 'Table', type: 'table', columns: ['fld_title001'], filters: [], sorts: [], archived: false }] }; var original = { id: 'rec_pending1', revision: 1, values: { fld_title001: 'Original' }, updatedAt: 1 };
  await reply(page, { type: 'knowledge_list', requestId: list.requestId, files: [database], drafts: [] }); await page.getByRole('button', { name: 'Pending', exact: true }).click(); var read = await lastSent(page, 'knowledge_db_read'); await reply(page, { type: 'knowledge_db_content', requestId: read.requestId, database: database }); var query = await lastSent(page, 'knowledge_db_query'); await reply(page, { type: 'knowledge_db_query_results', requestId: query.requestId, databaseId: database.id, databaseRevision: 3, records: [original], totals: { count: 1, sums: {} }, nextCursor: null }); await page.locator('[data-db-record="rec_pending1"]').click(); var recordRead = await lastSent(page, 'knowledge_db_record_read'); await reply(page, { type: 'knowledge_db_record_content', requestId: recordRead.requestId, database: database, record: original, title: 'Original', history: [] }); await page.locator('[data-db-edit-record]').click();
  var title = page.locator('[data-db-field="fld_title001"]'); await title.fill('First'); await page.locator('[data-db-save-record]').click(); var first = await lastSent(page, 'knowledge_db_record_update'); await title.fill('Later'); await title.evaluate(function (input) { input.focus(); input.setSelectionRange(3, 3); }); await page.locator('[data-db-save-record]').click(); var retry = await lastSent(page, 'knowledge_db_record_update'); assert.equal(retry.operationId, first.operationId); assert.deepEqual(retry.values, first.values);
  await title.evaluate(function (input) { input.focus(); input.setSelectionRange(3, 3); }); var committed = { id: original.id, revision: 2, values: { fld_title001: 'First' }, updatedAt: 2 }; await reply(page, { type: 'knowledge_db_record_updated', requestId: retry.requestId, databaseRevision: 4, record: committed }); assert.equal(await title.inputValue(), 'Later'); assert.equal(await page.evaluate(function () { return document.activeElement.selectionStart; }), 3); await reply(page, { type: 'knowledge_db_record_updated', requestId: first.requestId, databaseRevision: 4, record: committed }); assert.equal(await title.inputValue(), 'Later');
  await page.locator('[data-db-save-record]').click(); var later = await lastSent(page, 'knowledge_db_record_update'); assert.notEqual(later.operationId, first.operationId); assert.equal(later.expectedRevision, 2); assert.equal(later.values.fld_title001, 'Later'); await page.locator('[data-db-save-record]').click(); var laterRetry = await lastSent(page, 'knowledge_db_record_update'); assert.equal(laterRetry.operationId, later.operationId); assert.deepEqual(laterRetry.values, later.values); var laterCommitted = { id: original.id, revision: 3, values: { fld_title001: 'Later' }, updatedAt: 3 }; await reply(page, { type: 'knowledge_db_record_updated', requestId: later.requestId, databaseRevision: 5, record: laterCommitted }); assert.equal(await page.locator('[data-db-field="fld_title001"]').count(), 0); await reply(page, { type: 'knowledge_db_record_updated', requestId: laterRetry.requestId, databaseRevision: 5, record: laterCommitted }); assert.equal(await page.locator('[data-db-field="fld_title001"]').count(), 0);
  await page.locator('[data-db-edit-record]').click(); var socketTitle = page.locator('[data-db-field="fld_title001"]'); await socketTitle.fill('Socket later'); await page.locator('[data-db-save-record]').click(); var socketFirst = await lastSent(page, 'knowledge_db_record_update'); await page.evaluate(function () { window.setKnowledgeWs({ readyState: 1, send: function (raw) { window.sent.push(JSON.parse(raw)); } }); }); await page.locator('[data-db-save-record]').click(); var socketRetry = await lastSent(page, 'knowledge_db_record_update'); assert.equal(socketRetry.operationId, socketFirst.operationId); assert.deepEqual(socketRetry.values, socketFirst.values); var socketCommitted = { id: original.id, revision: 4, values: { fld_title001: 'Socket later' }, updatedAt: 4 }; await reply(page, { type: 'knowledge_db_record_updated', requestId: socketFirst.requestId, databaseRevision: 6, record: socketCommitted }); assert.equal(await socketTitle.inputValue(), 'Socket later'); await reply(page, { type: 'knowledge_db_record_updated', requestId: socketRetry.requestId, databaseRevision: 6, record: socketCommitted }); assert.equal(await page.locator('[data-db-field="fld_title001"]').count(), 0);
});

test('pending database creation keeps one immutable name and does not clear a newer draft', { timeout: 120000 }, async function (t) {
  var playwright = playwrightOrNull(); if (!playwright) { t.skip('playwright is not installed'); return; }
  var browser; try { browser = await playwright.chromium.launch(); } catch (error) { t.skip('Chromium is not available: ' + error.message); return; }
  t.after(function () { return browser.close(); }); var server = await serve(t); var page = await browser.newPage({ viewport: { width: 1280, height: 800 } }); await page.goto('http://127.0.0.1:' + server.address().port); await page.waitForFunction(function () { return window.ready; }); var list = await lastSent(page, 'knowledge_list'); await reply(page, { type: 'knowledge_list', requestId: list.requestId, files: [], drafts: [] });
  await page.locator('[data-knowledge-new]').click(); await page.getByRole('menuitem', { name: /New database/ }).click(); var name = page.locator('[data-db-new-name]'); await name.fill('First database'); await page.locator('[data-db-create-submit]').click(); var first = await lastSent(page, 'knowledge_db_create'); assert.equal(await name.isDisabled(), true); await page.locator('[data-db-create-submit]').click(); var retry = await lastSent(page, 'knowledge_db_create'); assert.equal(retry.operationId, first.operationId); assert.equal(retry.name, 'First database');
  await page.locator('[data-db-create-cancel]').click(); await page.locator('[data-knowledge-new]').click(); await page.getByRole('menuitem', { name: /New database/ }).click(); var newerName = page.locator('[data-db-new-name]'); await newerName.fill('Newer draft'); await newerName.evaluate(function (input) { input.focus(); input.setSelectionRange(5, 5); }); var created = { id: 'db_created99', itemType: 'db', name: 'First database', revision: 1, writable: true, recordCount: 0, schema: [{ id: 'fld_created1', name: 'Name', type: 'title', required: true, archived: false }], views: [{ id: 'view_created1', name: 'Table', type: 'table', columns: ['fld_created1'], filters: [], sorts: [], archived: false }] }; await reply(page, { type: 'knowledge_db_created', requestId: first.requestId, database: created }); assert.equal(await newerName.inputValue(), 'Newer draft'); assert.equal(await page.evaluate(function () { return document.activeElement.selectionStart; }), 5); await reply(page, { type: 'knowledge_db_created', requestId: retry.requestId, database: created }); assert.equal(await newerName.inputValue(), 'Newer draft'); assert.equal(await page.evaluate(function () { return document.activeElement.selectionStart; }), 5); assert.match(await page.locator('#mate-knowledge-workbench').getAttribute('class'), /panel-fullscreen/);
});

test('duplicate database create acknowledgement preserves the opened database draft state', { timeout: 120000 }, async function (t) {
  var playwright = playwrightOrNull(); if (!playwright) { t.skip('playwright is not installed'); return; }
  var browser; try { browser = await playwright.chromium.launch(); } catch (error) { t.skip('Chromium is not available: ' + error.message); return; }
  t.after(function () { return browser.close(); }); var server = await serve(t); var page = await browser.newPage({ viewport: { width: 1280, height: 800 } }); await page.goto('http://127.0.0.1:' + server.address().port); await page.waitForFunction(function () { return window.ready; }); var list = await lastSent(page, 'knowledge_list'); await reply(page, { type: 'knowledge_list', requestId: list.requestId, files: [], drafts: [] });
  await page.locator('[data-knowledge-new]').click(); await page.getByRole('menuitem', { name: /New database/ }).click(); await page.locator('[data-db-new-name]').fill('Duplicate safe'); await page.locator('[data-db-create-submit]').click(); var first = await lastSent(page, 'knowledge_db_create'); await page.locator('[data-db-create-submit]').click(); var retry = await lastSent(page, 'knowledge_db_create'); var created = { id: 'db_duplicate1', itemType: 'db', name: 'Duplicate safe', revision: 1, writable: true, recordCount: 0, schema: [{ id: 'fld_created1', name: 'Name', type: 'title', required: true, archived: false }], views: [{ id: 'view_created1', name: 'Table', type: 'table', columns: ['fld_created1'], filters: [], sorts: [], archived: false }] };
  await reply(page, { type: 'knowledge_db_created', requestId: first.requestId, database: created }); await page.locator('[data-db-add-record]').click(); var title = page.locator('[data-db-field="fld_created1"]'); await title.fill('Unsaved after create'); await title.evaluate(function (input) { input.focus(); input.setSelectionRange(7, 7); }); await page.evaluate(function () { var store = window.knowledge.store; var all = Object.assign({}, store.get('mateKnowledgeWorkspaces')); var workspace = Object.assign({}, all['mate-fixture']); var drafts = Object.assign({}, workspace.drafts); drafts['local:db_duplicate1'] = Object.assign({}, drafts['local:db_duplicate1'], { preservedMarker: 'keep' }); workspace.drafts = drafts; all['mate-fixture'] = workspace; store.set({ mateKnowledgeWorkspaces: all }); });
  await reply(page, { type: 'knowledge_db_created', requestId: retry.requestId, database: created }); var preserved = await page.evaluate(function () { var store = window.knowledge.store; return { edit: store.get('mateKnowledgeDatabaseWorkspaces')['mate-fixture'].databases.db_duplicate1.edit, draft: store.get('mateKnowledgeWorkspaces')['mate-fixture'].drafts['local:db_duplicate1'] }; }); assert.equal(preserved.edit.values.fld_created1, 'Unsaved after create'); assert.equal(preserved.draft.preservedMarker, 'keep'); assert.equal(await title.inputValue(), 'Unsaved after create'); assert.equal(await page.evaluate(function () { return document.activeElement.selectionStart; }), 7); assert.match(await page.locator('#mate-knowledge-workbench').getAttribute('class'), /panel-fullscreen/);
});
