var test = require("node:test");
var assert = require("node:assert/strict");
var attachSessions = require("../lib/project-sessions").attachSessions;
var attachPermissions = require("../lib/users-permissions").attachPermissions;

function fixture(options) {
  var calls = [];
  var actor = { id: "member", role: "member", permissions: { sessionDelete: options.deletePermission !== false } };
  var admin = { id: "admin", role: "admin" };
  var users = attachPermissions({
    findUserById: function (id) { return id === admin.id ? admin : actor; },
  });
  users.isMultiUser = function () { return options.multiUser !== false; };
  var session = {
    localId: 2, ownerId: options.ownerId, sessionVisibility: options.visibility,
    title: "Original", titleProvisional: true, titleAutoGenerated: true,
    mode: "tui", terminalId: 17, cliSessionId: "provider-session",
    _titleWatcherStop: function () { calls.push("watcher"); },
  };
  var sessions = new Map([[2, session]]);
  var handler = attachSessions({
    cwd: "/project", opts: {}, sdk: {}, clients: new Set(), usersModule: users,
    getProjectAccess: function () { return options.project || { visibility: "public" }; },
    sm: {
      sessions: sessions,
      deleteSession: function (id) { calls.push("delete"); sessions.delete(id); },
      saveSessionFile: function () { calls.push("save"); },
      notifySessionRenamed: function () { calls.push("notify"); },
      broadcastSessionList: function () { calls.push("broadcast"); },
    },
    tm: { close: function () { calls.push("pty"); } },
    adapter: { renameSession: function () { calls.push("sdk"); return Promise.resolve(); } },
    sendTo: function () { calls.push("error"); },
  });
  var ws = options.anonymous ? {} : { _clayUser: options.admin ? admin : actor };
  return { calls: calls, session: session, sessions: sessions, run: function (type, id) {
    return handler.handleSessionsMessage(ws, { type: type, id: id === undefined ? 2 : id, title: "Updated" });
  } };
}

["rename_session", "delete_session"].forEach(function (type) {
  [
    { name: "another member's private session", ownerId: "other", visibility: "private" },
    { name: "implicit private session", ownerId: "other" },
    { name: "legacy ownerless session" },
    { name: "missing authenticated identity", ownerId: "member", anonymous: true },
    { name: "revoked project access", ownerId: "member", project: { visibility: "private", ownerId: "other" } },
  ].forEach(function (scenario) {
    test(type + " rejects " + scenario.name + " before any side effects", function () {
      var f = fixture(scenario);
      assert.equal(f.run(type), true);
      assert.deepEqual(f.calls, []);
      assert.equal(f.sessions.has(2), true);
      assert.equal(f.session.title, "Original");
      assert.equal(f.session.titleProvisional, true);
      assert.equal(f.session.titleAutoGenerated, true);
      assert.equal(f.session.titleManuallySet, undefined);
      assert.equal(typeof f.session._titleWatcherStop, "function");
    });
  });

  [
    { name: "owner", ownerId: "member", visibility: "private" },
    { name: "administrator", ownerId: "other", visibility: "private", admin: true },
    { name: "explicitly shared session", ownerId: "other", visibility: "shared" },
    { name: "single-user session", multiUser: false, anonymous: true },
  ].forEach(function (scenario) {
    test(type + " allows " + scenario.name, function () {
      var f = fixture(scenario);
      assert.equal(f.run(type), true);
      if (type === "delete_session") {
        assert.deepEqual(f.calls, ["pty", "watcher", "delete"]);
        assert.equal(f.sessions.has(2), false);
      } else {
        assert.deepEqual(f.calls, ["save", "notify", "broadcast", "sdk"]);
        assert.equal(f.session.title, "Updated");
        assert.equal(f.session.titleProvisional, false);
        assert.equal(f.session.titleAutoGenerated, false);
        assert.equal(f.session.titleManuallySet, true);
      }
    });
  });

  test(type + " ignores nonexistent session IDs", function () {
    var f = fixture({ ownerId: "member" });
    assert.equal(f.run(type, 99), true);
    assert.deepEqual(f.calls, []);
  });
});

test("delete_session still requires the sessionDelete permission for owners", function () {
  var f = fixture({ ownerId: "member", deletePermission: false });
  assert.equal(f.run("delete_session"), true);
  assert.deepEqual(f.calls, ["error"]);
  assert.equal(f.sessions.has(2), true);
});
