var test = require("node:test");
var assert = require("node:assert/strict");
var attach = require("../lib/session-title-generator").attachSessionTitleGenerator;

function fixture(adapter) {
  var sessions = new Map();
  var saved = 0;
  var broadcasts = 0;
  var sm = {
    sessions: sessions,
    saveSessionFile: function () { saved++; },
    broadcastSessionList: function () { broadcasts++; },
  };
  var generator = attach({
    sm: sm,
    cwd: "/tmp/project",
    getAdapter: function () { return adapter; },
    getLinuxUser: function () { return "clay"; },
    getRuntimeEnv: function () { return { TEST: "1" }; },
  });
  return { sessions: sessions, generator: generator, counts: function () { return { saved: saved, broadcasts: broadcasts }; } };
}

function session() {
  return {
    localId: 1,
    title: "Plan the launch campaign",
    titleAutoGenerated: false,
    titleManuallySet: false,
    cliSessionId: "provider-session",
    history: [{ type: "user_message", text: "Plan the launch campaign" }],
  };
}

test("uses selected vendor adapter and persists/broadcasts provider rename", async function () {
  var renamed = [];
  var f = fixture({
    generateTitle: function () { return Promise.resolve("Launch campaign plan"); },
    renameSession: function (id, title, opts) { renamed.push([id, title, opts.dir]); return Promise.resolve(); },
  });
  var s = session();
  f.sessions.set(s.localId, s);
  assert.equal(await f.generator.generate(s), true);
  assert.equal(s.title, "Launch campaign plan");
  assert.deepEqual(renamed, [["provider-session", "Launch campaign plan", "/tmp/project"]]);
  assert.deepEqual(f.counts(), { saved: 1, broadcasts: 1 });
});

test("bridge-protected seeded titles are not regenerated by the coordinator", async function () {
  var calls = 0;
  var f = fixture({ generateTitle: function () { calls++; return Promise.resolve("Replacement title"); } });
  var s = session();
  s.titleAutoGenerated = true;
  s.titleProvisional = false;
  f.sessions.set(s.localId, s);
  assert.equal(await f.generator.generate(s), false);
  assert.equal(calls, 0);
  assert.equal(s.title, "Plan the launch campaign");
});

test("does not duplicate an in-flight request and retries later failures up to the cap", async function () {
  var resolveFirst;
  var calls = 0;
  var f = fixture({
    generateTitle: function () {
      calls++;
      if (calls === 1) return new Promise(function (resolve) { resolveFirst = resolve; });
      return Promise.resolve("");
    },
    renameSession: function () { return Promise.resolve(); },
  });
  var s = session();
  f.sessions.set(s.localId, s);
  var first = f.generator.generate(s);
  await Promise.resolve();
  assert.equal(f.generator.generate(s), false);
  resolveFirst("");
  await first;
  assert.equal(await f.generator.generate(s), false);
  assert.equal(await f.generator.generate(s), false);
  assert.equal(await f.generator.generate(s), false);
  assert.equal(calls, 3);
});

test("manual rename and removal win over a pending generated title", async function () {
  var resolveTitle;
  var f = fixture({
    generateTitle: function () { return new Promise(function (resolve) { resolveTitle = resolve; }); },
    renameSession: function () { return Promise.resolve(); },
  });
  var s = session();
  f.sessions.set(s.localId, s);
  var pending = f.generator.generate(s);
  await Promise.resolve();
  s.title = "Human name";
  s.titleManuallySet = true;
  resolveTitle("Generated name");
  assert.equal(await pending, false);
  assert.equal(s.title, "Human name");

  var deleted = session();
  f.sessions.set(deleted.localId, deleted);
  var deletedPending = f.generator.generate(deleted);
  await Promise.resolve();
  f.sessions.delete(deleted.localId);
  resolveTitle("Late name");
  assert.equal(await deletedPending, false);
  assert.equal(deleted.title, "Plan the launch campaign");
});

test("Split Workers are excluded even if a completion reaches the coordinator", async function () {
  var calls = 0;
  var f = fixture({ generateTitle: function () { calls++; return Promise.resolve("Worker title"); } });
  var s = session();
  s.sessionProvenance = { kind: "worker" };
  f.sessions.set(s.localId, s);
  assert.equal(await f.generator.generate(s), false);
  assert.equal(calls, 0);
});

test("a session that becomes a Split Worker while pending cannot be titled", async function () {
  var resolveTitle;
  var f = fixture({
    generateTitle: function () { return new Promise(function (resolve) { resolveTitle = resolve; }); },
    renameSession: function () { return Promise.resolve(); },
  });
  var s = session();
  f.sessions.set(s.localId, s);
  var pending = f.generator.generate(s);
  await Promise.resolve();
  s.sessionProvenance = { kind: "worker" };
  resolveTitle("Late Worker title");
  assert.equal(await pending, false);
  assert.equal(s.title, "Plan the launch campaign");
});
