var test = require("node:test");
var assert = require("node:assert/strict");
var fs = require("node:fs");
var os = require("node:os");
var path = require("node:path");
var policy = require("../lib/session-title-policy");
var attachMessageProcessor = require("../lib/sdk-message-processor").attachMessageProcessor;
var createSessionManager = require("../lib/sessions").createSessionManager;

test("global-search titles use the visible query instead of provider boilerplate", function () {
  var transport = "This conversation began in Clay Studio's global search. Respond as Clay. User request: Find fruit";
  var apples = policy.selectInitialTitle({
    history: [{ type: "user_message", text: "Find my conversation about apple harvest planning" }],
  }, transport);
  var invoices = policy.selectInitialTitle({
    history: [{ type: "user_message", text: "Find the discussion about overdue client invoices" }],
  }, transport);

  assert.equal(apples.title, "Find my conversation about apple harvest planning");
  assert.equal(invoices.title, "Find the discussion about overdue client invoices");
  assert.notEqual(apples.title, invoices.title);
  assert.equal(apples.provisional, true);
});

test("provisional labels are distinct from fixed seeded titles", function () {
  assert.deepEqual(policy.selectInitialTitle({ title: "Nightly release" }, "ignored transport"), {
    title: "Nightly release",
    provisional: false,
  });
  assert.deepEqual(policy.selectInitialTitle({ history: [] }, "short"), {
    title: null,
    provisional: false,
  });
});

test("a first-message label remains provisional when startQuery runs afterward", function () {
  var session = {
    title: "Plan the launch campaign",
    titleProvisional: true,
    history: [{ type: "user_message", text: "Plan the launch campaign" }],
  };
  assert.deepEqual(policy.selectInitialTitle(session, "ignored transport"), {
    title: "Plan the launch campaign",
    provisional: true,
  });
  session.titleProvisional = false;
  assert.deepEqual(policy.selectInitialTitle(session, "ignored transport"), {
    title: "Plan the launch campaign",
    provisional: false,
  });
});

test("legacy global-search boilerplate titles repair from visible history", function () {
  var session = {
    title: "This conversation began in Clay Studio's global search. Resp",
    titleAutoGenerated: true,
    history: [{ type: "user_message", text: "Find the hiring plan from last month" }],
  };
  assert.equal(policy.repairLegacySearchTitle(session), true);
  assert.equal(session.title, "Find the hiring plan from last month");
  assert.equal(session.titleAutoGenerated, false);
  assert.equal(policy.repairLegacySearchTitle(session), false, "repair runs only once");
});

test("regular and Home titles become semantic after the first completed exchange", function () {
  assert.equal(policy.generationTurn(true), 1);
  assert.equal(policy.generationTurn(false), 1);
});

function titleProcessor(isMate, onAutoTitle) {
  return attachMessageProcessor({
    sm: {
      sendAndRecord: function () {},
      sendToSession: function () {},
      broadcastSessionList: function () {},
    },
    send: function () {},
    slug: isMate ? "mate-clay" : "project",
    isMate: isMate,
    mateDisplayName: isMate ? "Clay" : "",
    getNotificationsModule: function () { return null; },
    shouldSuppressResponseNotification: function () { return true; },
    onProcessingChanged: function () {},
    onAutoTitle: onAutoTitle,
  });
}

function completedSession() {
  return {
    localId: 1,
    history: [{ type: "user_message", text: "Plan the launch campaign" }],
    blocks: {},
    sentToolResults: {},
    pendingPermissions: {},
    pendingElicitations: {},
    pendingAskUser: {},
    activeTaskToolIds: {},
    taskIdMap: {},
    responsePreview: "Here is a plan.",
    isProcessing: true,
    titleAutoGenerated: false,
    titleManuallySet: false,
    turnCount: 0,
  };
}

test("completed Home turns request a semantic title immediately", function () {
  var calls = 0;
  var processor = titleProcessor(true, function () { calls++; });
  processor.processSDKMessage(completedSession(), { yokeType: "result", cost: 1, duration: 1 });
  assert.equal(calls, 1);
});

test("ordinary project sessions request a semantic title after the first turn", function () {
  var calls = 0;
  var processor = titleProcessor(false, function () { calls++; });
  var session = completedSession();
  processor.processSDKMessage(session, { yokeType: "result", cost: 1, duration: 1 });
  assert.equal(calls, 1);
});

test("processor excludes Split Workers before requesting a title", function () {
  var calls = 0;
  var processor = titleProcessor(false, function () { calls++; });
  var session = completedSession();
  session.sessionProvenance = { kind: "worker" };
  processor.processSDKMessage(session, { yokeType: "result", cost: 1, duration: 1 });
  assert.equal(calls, 0);
});

test("query startup adopts provisional titles without marking them generated", function () {
  var bridge = fs.readFileSync(path.join(__dirname, "..", "lib", "sdk-bridge.js"), "utf8");
  assert.match(bridge, /sessionTitlePolicy\.selectInitialTitle\(session, text\)/);
  assert.match(bridge, /session\.titleProvisional = initialTitleProvisional/);
  assert.match(bridge, /session\.titleAutoGenerated = !initialTitleProvisional/);
});

test("recordSessionTitle marks the first-message label with persisted provenance", function () {
  var source = fs.readFileSync(path.join(__dirname, "..", "lib", "project-user-message.js"), "utf8");
  assert.match(source, /session\.titleProvisional = true/);
  assert.match(source, /recordSessionTitle\(\)/);
  assert.match(source, /session\.history\.push\(userMsg2\)/);
});

test("title provenance survives fresh storage roundtrip", function (t) {
  var root = fs.mkdtempSync(path.join(os.tmpdir(), "clay-title-roundtrip-"));
  t.after(function () { fs.rmSync(root, { recursive: true, force: true }); });
  var options = {
    cwd: path.join(root, "project"),
    sessionsBase: path.join(root, "sessions"),
    cliSessionsDir: path.join(root, "cli"),
    send: function () {},
  };
  var first = createSessionManager(options);
  var provisional = first.createSessionRaw({ cliSessionId: "provisional", vendor: "claude" });
  provisional.title = "First message label";
  provisional.titleProvisional = true;
  var generated = first.createSessionRaw({ cliSessionId: "generated", vendor: "codex" });
  generated.title = "Generated topic";
  generated.titleAutoGenerated = true;
  var manual = first.createSessionRaw({ cliSessionId: "manual", vendor: "claude" });
  manual.title = "Pinned name";
  manual.titleManuallySet = true;
  first.saveSessionFile(provisional);
  first.saveSessionFile(generated);
  first.saveSessionFile(manual);

  var second = createSessionManager(options);
  var restored = Array.from(second.sessions.values());
  var byId = function (id) { return restored.filter(function (session) { return session.cliSessionId === id; })[0]; };
  assert.equal(byId("provisional").titleProvisional, true);
  assert.equal(byId("generated").titleAutoGenerated, true);
  assert.equal(byId("manual").titleManuallySet, true);
  assert.equal(byId("manual").titleProvisional, false);
  assert.equal(policy.selectInitialTitle(byId("provisional"), "ignored").provisional, true);
  assert.equal(policy.selectInitialTitle(byId("generated"), "ignored").provisional, false);
  assert.equal(policy.selectInitialTitle(byId("manual"), "ignored").provisional, false);
});

test("unknown legacy titles remain protected and are not rewritten", function (t) {
  var root = fs.mkdtempSync(path.join(os.tmpdir(), "clay-title-legacy-"));
  t.after(function () { fs.rmSync(root, { recursive: true, force: true }); });
  var cwd = path.join(root, "project");
  var encoded = require("../lib/utils").encodeCwd(cwd);
  var sessionsDir = path.join(root, "sessions", encoded);
  fs.mkdirSync(sessionsDir, { recursive: true });
  fs.writeFileSync(path.join(sessionsDir, "legacy.jsonl"), [
    JSON.stringify({ type: "meta", localId: 1, cliSessionId: "legacy", title: "Custom legacy name", createdAt: 1 }),
    JSON.stringify({ type: "user_message", text: "A historical request" }),
  ].join("\n") + "\n");
  var manager = createSessionManager({ cwd: cwd, sessionsBase: path.join(root, "sessions"), cliSessionsDir: path.join(root, "cli"), send: function () {} });
  var restored = Array.from(manager.sessions.values())[0];
  assert.equal(restored.title, "Custom legacy name");
  assert.equal(restored.titleProvisional, false);
  assert.equal(restored.titleAutoGenerated, false);
  assert.equal(restored.titleManuallySet, true);
  assert.equal(policy.selectInitialTitle(restored, "ignored").provisional, false);
});

test("completed turns retry recorded OAuth error titles but preserve manual titles", function () {
  var calls = 0;
  var processor = titleProcessor(false, function () { calls++; });
  var session = completedSession();
  session.titleAutoGenerated = true;
  session.title = "Failed to authenticate: OAuth session expired and could not be refreshed";
  processor.processSDKMessage(session, { yokeType: "result" });
  assert.equal(calls, 1);
  session.titleManuallySet = true;
  processor.processSDKMessage(session, { yokeType: "result" });
  assert.equal(calls, 1);
  session.titleManuallySet = false;
  session.title = "Authentication failure investigation";
  processor.processSDKMessage(session, { yokeType: "result" });
  assert.equal(calls, 1);
});
